import { Table } from "antd";

const header = [
  {
    title: "N° Comprobante",
    dataIndex: "Comprobante",
    key: "Comprobante",
  },
  {
    title: "RUC",
    key: "RUC",
    dataIndex: "RUC",
  },
  {
    title: "Descripcion",
    key: "Descripcion",
    dataIndex: "Descripcion",
  },
  {
    title: "Subtotal",
    key: "Subtotal",
    dataIndex: "Subtotal",
  },
  {
    title: "Total",
    key: "Total",
    dataIndex: "Total",
  },
  {
    title: "IGV",
    key: "IGV",
    dataIndex: "IGV",
  },
  {
    title: "Fecha",
    key: "Fecha",
    dataIndex: "Fecha",
  },
];

const data = [
  {
    key: "1",
    Comprobante: "1c",
    RUC: "1r",
    Descripcion:
      "alguna descripcion alguna descripcion alguna descripcion alguna descripcion alguna descripcion alguna descripcion alguna descripcion alguna descripcion alguna descripcion ",
    Subtotal: "1s",
    Total: "1t",
    IGV: "1i",
    Fecha: "1f",
  },
  {
    key: "2",
    Comprobante: "2c",
    RUC: "2r",
    Descripcion: "2d",
    Subtotal: "2s",
    Total: "2t",
    IGV: "2i",
    Fecha: "2f",
  },
  {
    key: "3",
    Comprobante: "3c",
    RUC: "3r",
    Descripcion: "3d",
    Subtotal: "3s",
    Total: "3t",
    IGV: "3i",
    Fecha: "3f",
  },
  {
    key: "4",
    Comprobante: "4c",
    RUC: "4r",
    Descripcion: "4d",
    Subtotal: "4s",
    Total: "4t",
    IGV: "4i",
    Fecha: "4f",
  },
  {
    key: "5",
    Comprobante: "1c",
    RUC: "1r",
    Descripcion: "1d",
    Subtotal: "1s",
    Total: "1t",
    IGV: "1i",
    Fecha: "1f",
  },
  {
    key: "6",
    Comprobante: "2c",
    RUC: "2r",
    Descripcion: "2d",
    Subtotal: "2s",
    Total: "2t",
    IGV: "2i",
    Fecha: "2f",
  },
  {
    key: "7",
    Comprobante: "3c",
    RUC: "3r",
    Descripcion: "3d",
    Subtotal: "3s",
    Total: "3t",
    IGV: "3i",
    Fecha: "3f",
  },
  {
    key: "8",
    Comprobante: "4c",
    RUC: "4r",
    Descripcion: "4d",
    Subtotal: "4s",
    Total: "4t",
    IGV: "4i",
    Fecha: "4f",
  },
  {
    key: "9",
    Comprobante: "1c",
    RUC: "1r",
    Descripcion: "1d",
    Subtotal: "1s",
    Total: "1t",
    IGV: "1i",
    Fecha: "1f",
  },
  {
    key: "10",
    Comprobante: "2c",
    RUC: "2r",
    Descripcion: "2d",
    Subtotal: "2s",
    Total: "2t",
    IGV: "2i",
    Fecha: "2f",
  },
  {
    key: "11",
    Comprobante: "3c",
    RUC: "3r",
    Descripcion: "3d",
    Subtotal: "3s",
    Total: "3t",
    IGV: "3i",
    Fecha: "3f",
  },
  {
    key: "12",
    Comprobante: "4c",
    RUC: "4r",
    Descripcion: "4d",
    Subtotal: "4s",
    Total: "4t",
    IGV: "4i",
    Fecha: "4f",
  },
  {
    key: "13",
    Comprobante: "1c",
    RUC: "1r",
    Descripcion: "1d",
    Subtotal: "1s",
    Total: "1t",
    IGV: "1i",
    Fecha: "1f",
  },
  {
    key: "14",
    Comprobante: "2c",
    RUC: "2r",
    Descripcion: "2d",
    Subtotal: "2s",
    Total: "2t",
    IGV: "2i",
    Fecha: "2f",
  },
  {
    key: "15",
    Comprobante: "3c",
    RUC: "3r",
    Descripcion: "3d",
    Subtotal: "3s",
    Total: "3t",
    IGV: "3i",
    Fecha: "3f",
  },
  {
    key: "16",
    Comprobante: "4c",
    RUC: "4r",
    Descripcion: "4d",
    Subtotal: "4s",
    Total: "4t",
    IGV: "4i",
    Fecha: "4f",
  },
  {
    key: "17",
    Comprobante: "1c",
    RUC: "1r",
    Descripcion: "1d",
    Subtotal: "1s",
    Total: "1t",
    IGV: "1i",
    Fecha: "1f",
  },
  {
    key: "18",
    Comprobante: "2c",
    RUC: "2r",
    Descripcion: "2d",
    Subtotal: "2s",
    Total: "2t",
    IGV: "2i",
    Fecha: "2f",
  },
  {
    key: "19",
    Comprobante: "3c",
    RUC: "3r",
    Descripcion: "3d",
    Subtotal: "3s",
    Total: "3t",
    IGV: "3i",
    Fecha: "3f",
  },
  {
    key: "20",
    Comprobante: "4c",
    RUC: "4r",
    Descripcion: "4d",
    Subtotal: "4s",
    Total: "4t",
    IGV: "4i",
    Fecha: "4f",
  },
  {
    key: "21",
    Comprobante: "1c",
    RUC: "1r",
    Descripcion: "1d",
    Subtotal: "1s",
    Total: "1t",
    IGV: "1i",
    Fecha: "1f",
  },
  {
    key: "22",
    Comprobante: "2c",
    RUC: "2r",
    Descripcion: "2d",
    Subtotal: "2s",
    Total: "2t",
    IGV: "2i",
    Fecha: "2f",
  },
  {
    key: "23",
    Comprobante: "3c",
    RUC: "3r",
    Descripcion: "3d",
    Subtotal: "3s",
    Total: "3t",
    IGV: "3i",
    Fecha: "3f",
  },
  {
    key: "24",
    Comprobante: "4c",
    RUC: "4r",
    Descripcion: "4d",
    Subtotal: "4s",
    Total: "4t",
    IGV: "4i",
    Fecha: "4f",
  },
  {
    key: "25",
    Comprobante: "1c",
    RUC: "1r",
    Descripcion: "1d",
    Subtotal: "1s",
    Total: "1t",
    IGV: "1i",
    Fecha: "1f",
  },
  {
    key: "26",
    Comprobante: "2c",
    RUC: "2r",
    Descripcion: "2d",
    Subtotal: "2s",
    Total: "2t",
    IGV: "2i",
    Fecha: "2f",
  },
  {
    key: "27",
    Comprobante: "3c",
    RUC: "3r",
    Descripcion: "3d",
    Subtotal: "3s",
    Total: "3t",
    IGV: "3i",
    Fecha: "3f",
  },
  {
    key: "28",
    Comprobante: "4c",
    RUC: "4r",
    Descripcion: "4d",
    Subtotal: "4s",
    Total: "4t",
    IGV: "4i",
    Fecha: "4f",
  },
  {
    key: "29",
    Comprobante: "1c",
    RUC: "1r",
    Descripcion: "1d",
    Subtotal: "1s",
    Total: "1t",
    IGV: "1i",
    Fecha: "1f",
  },
  {
    key: "30",
    Comprobante: "2c",
    RUC: "2r",
    Descripcion: "2d",
    Subtotal: "2s",
    Total: "2t",
    IGV: "2i",
    Fecha: "2f",
  },
  {
    key: "31",
    Comprobante: "3c",
    RUC: "3r",
    Descripcion: "3d",
    Subtotal: "3s",
    Total: "3t",
    IGV: "3i",
    Fecha: "3f",
  },
  {
    key: "32",
    Comprobante: "4c",
    RUC: "4r",
    Descripcion: "4d",
    Subtotal: "4s",
    Total: "4t",
    IGV: "4i",
    Fecha: "4f",
  },
];

const TableDocument = () => {
  return (
    <Table
      columns={header}
      dataSource={data}
      scroll={{
        y: "calc( 100vh - 260px )",
        x: 800,
      }}
      size="small"
    />
  );
};

export default TableDocument;
